DROP USER ORADB2;
create user Prasad  IDENTIFIED BY oracle;
grant CREATE SESSION,ALTER SESSION,ALTER USER,CREATE DATABASE LINK,
CREATE MATERIALIZED VIEW,CREATE PROCEDURE,CREATE PUBLIC SYNONYM,
CREATE ROLE,CREATE SEQUENCE,CREATE SYNONYM,CREATE TABLE,
CREATE TRIGGER,CREATE TYPE,CREATE VIEW,CREATE ANY INDEX,UNLIMITED TABLESPACE 
to Prasad;
  